"""
Shared State Definition
========================
Our pipeline has multiple agents running one after another. Each agent produces
some data that later agents need. For example:
    - Time parsing figures out the date range → log analysis needs that
      date range to know which S3 files to download
    - Log analysis finds events → the report agent needs those events
    - Retrieval finds relevant docs → the report agent needs those docs too

So we need a way for agents to SHARE DATA with each other. That's what
this file defines — the SHAPE of the shared data.

What is a TypedDict?
    A regular Python dictionary lets you put anything in it. Python won't
    complain if you accidentally write my_dict["nmae"] (typo) — it'll just
    crash at runtime.

    A TypedDict is a dictionary where you PRE-DEFINE what keys exist and
    what type each value is. It's like a form with labeled fields — you
    know exactly what goes where.

    Benefits:
    1. Documentation — anyone reading this file immediately sees every
       field the pipeline uses, what type it is, and what it represents
    2. Error catching — if an agent tries to access state["qurey"] (typo),
       your IDE will warn you before you even run the code

How the state flows through the pipeline:
    At the START of the pipeline, the state looks like:
        {
            "query": "What IAM changes happened yesterday?",
            "time_range": None,            # Not yet — Step 1 hasn't run
            "log_findings": None,          # Not yet — Step 2 hasn't run
            "relevant_categories": None,   # Not yet — Step 3 hasn't run
            "retrieved_docs": None,        # Not yet — Step 4 hasn't run
            "retrieval_confidence": 0.0,
            "retry_count": 0,
            "final_report": None,          # Not yet — Step 6 hasn't run
            "metadata": None,
        }

    Each agent reads what it needs, does its work, and returns a dict with
    its results. LangGraph MERGES that return dict into the shared state.

    After Step 1 runs, it returns {"time_range": {"start": "...", "end": "..."}}.
    LangGraph merges that in. Now time_range is no longer None.

    After Step 2 runs, it returns {"log_findings": {"events": [...], "summary": "..."}}.
    LangGraph merges that in too.

    By the time the pipeline reaches END, every field is filled in.

    "Optional" means "this can be None." Fields start as None and get
    filled in as their respective agents run.
"""

from typing import TypedDict, Optional


# ---------------------------------------------------------------------------
# Building Block Types
# These are small types used inside the main DocuGenState.
# ---------------------------------------------------------------------------

class TimeRange(TypedDict):
    """A time range with start and end timestamps. Created by Step 1 (Time Parsing).

    Example:
        {"start": "2026-02-06T00:00:00Z", "end": "2026-02-06T23:59:59Z"}
    """
    start: str  # ISO-8601 timestamp, e.g., "2026-02-06T00:00:00Z"
    end: str    # ISO-8601 timestamp, e.g., "2026-02-06T23:59:59Z"


class LogEvent(TypedDict):
    """One simplified CloudTrail event. Created by Step 2 (Log Analysis).

    Raw CloudTrail events have 50+ fields. We keep only these 7.

    Example:
        {
            "eventTime": "2026-02-06T14:23:00Z",
            "eventName": "CreateUser",
            "userName": "docugen-dev",        # WHO did it
            "sourceIP": "203.0.113.50",
            "region": "us-east-1",
            "category": "IAM_CHANGE",         # Our label (deterministic lookup)
            "targetResource": "test-final-user"  # WHAT was acted upon
        }
    """
    eventTime: str        # When the event happened
    eventName: str        # What action was performed (e.g., "CreateUser")
    userName: str         # Who performed the action (from userIdentity)
    sourceIP: str         # IP address of the actor
    region: str           # AWS region (e.g., "us-east-1")
    category: str         # Our category label (e.g., "IAM_CHANGE", "S3_CONFIG")
    targetResource: str   # What was acted upon (e.g., the user/bucket/role created)


class LogFindings(TypedDict):
    """A bundle of events plus a Claude-generated summary. Created by Step 2.

    Example:
        {
            "events": [LogEvent, LogEvent, ...],
            "summary": "3 IAM changes detected by user docugen-dev..."
        }
    """
    events: list[LogEvent]   # All the events found (significant first, noise at end)
    summary: str             # 2-3 sentence overview generated by Claude


class RetrievedDoc(TypedDict):
    """One document chunk retrieved from Pinecone. Created by Step 4 (Retrieval).

    This is a piece of AWS documentation that was found to be semantically
    similar to the search query. Used to ground the report in real docs.

    Example:
        {
            "content": "IAM users are identities you create in AWS...",
            "source": "iam-users-guide.md",
            "similarity": 0.65
        }
    """
    content: str       # The actual text chunk from the AWS doc
    source: str        # Which .md file it came from (cited in the report)
    similarity: float  # Cosine similarity score (0 to 1, higher = more relevant)


class ReportMetadata(TypedDict):
    """Metadata about a generated report. Created by Step 6 (Report Synthesis).

    Stored alongside the report in S3 for auditing and traceability.

    Example:
        {
            "timestamp": "2026-02-08T15:30:00Z",
            "model_used": "Claude 3.5 Sonnet",
            "confidence_score": 0.63,
            "sources_referenced": ["iam-users-guide.md", "iam-best-practices.md"],
            "report_id": "a1b2c3d4-..."
        }
    """
    timestamp: str                # When the report was generated
    model_used: str               # Which LLM wrote the report
    confidence_score: float       # Average similarity of retrieved docs
    sources_referenced: list[str] # Which doc files were cited
    report_id: str                # Unique identifier (UUID)


# ---------------------------------------------------------------------------
# Main State — The shared notebook passed through the entire pipeline
#
# Each field is filled in by a specific step:
#
#   Field                  | Filled by          | What it is
#   -----------------------|--------------------|---------------------------------
#   query                  | User (Streamlit)   | The original question
#   time_range             | Step 1             | Start/end timestamps
#   log_findings           | Step 2, updated 3  | Events + summary
#   relevant_categories    | Step 3             | Which categories match the question
#   retrieved_docs         | Step 4             | AWS doc chunks from Pinecone
#   retrieval_confidence   | Step 4             | Average similarity score
#   retry_count            | Step 5             | How many retrieval retries so far
#   final_report           | Step 6             | The Markdown report
#   metadata               | Step 6             | Report details for auditing
# ---------------------------------------------------------------------------

class DocuGenState(TypedDict):
    """The shared state that flows through the entire LangGraph pipeline.

    Think of this as a notebook that gets passed from agent to agent.
    Each agent reads what it needs, does its work, and writes its results back.
    Every agent can see what previous agents wrote.

    At the start, only "query" has a value. By the end, everything is filled in.
    """
    query: str                                          # The user's original question
    time_range: Optional[TimeRange]                     # Step 1: parsed date range
    log_findings: Optional[LogFindings]                 # Step 2+3: events and summary
    relevant_categories: Optional[list[str]]            # Step 3: e.g., ["IAM_CHANGE"]
    retrieved_docs: Optional[list[RetrievedDoc]]        # Step 4: docs from Pinecone
    retrieval_confidence: float                         # Step 4: avg similarity (0 to 1)
    retry_count: int                                    # Step 5: 0, 1, or 2
    final_report: Optional[str]                         # Step 6: the Markdown report
    metadata: Optional[ReportMetadata]                  # Step 6: report details
